-- ============================================
-- QRme ADMIN SUPREMACY SCHEMA
-- ============================================

-- 1. Enhanced Audit Log
CREATE TABLE IF NOT EXISTS admin_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id UUID REFERENCES auth.users(id),
    admin_email TEXT,
    action TEXT NOT NULL, -- VIEW, BAN, SUSPEND, RESET_POINTS, etc.
    target_type TEXT,    -- USER, IDENTITY, CODE
    target_id TEXT,      -- The ID of the target
    details JSONB,       -- Full context of the action
    ip_address TEXT,
    user_agent TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. User Status Tracking (In Profiles or Metadata)
-- Assuming we have a public profiles table or similar. Let's ensure a column exists.
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'active'; -- active, suspended, banned
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS ban_reason TEXT;

-- 3. Detailed Scan Logs (For Anti-Fraud)
CREATE TABLE IF NOT EXISTS scan_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id BIGINT REFERENCES public.shops(id) ON DELETE CASCADE,
    visitor_ip TEXT,
    visitor_ua TEXT,
    referrer TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. RPC for Comprehensive Admin Stats
CREATE OR REPLACE FUNCTION get_admin_dashboard_stats()
RETURNS JSON AS $$
DECLARE
    stats JSON;
BEGIN
    SELECT json_build_object(
        'counters', json_build_object(
            'users', (SELECT COUNT(*) FROM auth.users),
            'identities', (SELECT COUNT(*) FROM nexus_identities),
            'codes', (SELECT COUNT(*) FROM shops),
            'total_scans', (SELECT COALESCE(SUM(total_scans), 0) FROM shop_stats),
            'total_points', (SELECT COALESCE(SUM(total_points), 0) FROM user_points),
            'total_shares', (SELECT COALESCE(SUM(total_shares), 0) FROM user_points)
        ),
        'top_performers', json_build_object(
            'identity', (
                SELECT json_build_object('id', id, 'name', full_name) 
                FROM nexus_identities 
                ORDER BY created_at DESC LIMIT 1 -- Simplified for now
            ),
            'code', (
                SELECT json_build_object('id', s.id, 'name', s.name, 'scans', st.total_scans)
                FROM shops s
                JOIN shop_stats st ON s.id = st.shop_id
                ORDER BY st.total_scans DESC LIMIT 1
            )
        ),
        'recent_activity', (
            SELECT json_agg(act) FROM (
                SELECT action, admin_email, target_type, created_at 
                FROM admin_audit_logs 
                ORDER BY created_at DESC LIMIT 10
            ) act
        )
    ) INTO stats;
    
    RETURN stats;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
