-- ============================================
-- QRme V8.5 - FULL REFERRAL & LOCALIZATION SYSTEM
-- ============================================

-- 1. POINTS SYSTEM TABLES
CREATE TABLE IF NOT EXISTS user_points (
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    total_points INTEGER DEFAULT 0,
    total_shares INTEGER DEFAULT 0,
    last_share_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS share_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    share_channel TEXT, -- whatsapp, twitter, native, etc.
    points_awarded INTEGER DEFAULT 5,
    ip_hash TEXT, -- To prevent abuse from same IP
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. LOCALIZATION FOR SERVICES
ALTER TABLE code_services ADD COLUMN IF NOT EXISTS name_ar TEXT;
ALTER TABLE code_services ADD COLUMN IF NOT EXISTS name_en TEXT;

UPDATE code_services SET 
    name_ar = CASE 
        WHEN id = 'facebook' THEN 'فيسبوك'
        WHEN id = 'instagram' THEN 'انستجرام'
        WHEN id = 'whatsapp' THEN 'واتساب'
        WHEN id = 'telegram' THEN 'تيليجرام'
        WHEN id = 'twitter' THEN 'إكس (تويتر)'
        WHEN id = 'tiktok' THEN 'تيك توك'
        WHEN id = 'youtube' THEN 'يوتيوب'
        WHEN id = 'linkedin' THEN 'لينكد إن'
        WHEN id = 'website' THEN 'موقع إلكتروني'
        WHEN id = 'phone' THEN 'هاتف'
        WHEN id = 'email' THEN 'بريد إلكتروني'
        WHEN id = 'snapchat' THEN 'سناب شات'
        ELSE name
    END,
    name_en = name;

UPDATE code_services SET name_en = 'X (Twitter)' WHERE id = 'twitter';

-- 3. USER RPCs - DROP FIRST to avoid return type conflicts
DROP FUNCTION IF EXISTS get_user_points();
CREATE OR REPLACE FUNCTION get_user_points()
RETURNS JSONB AS $$
DECLARE
    v_points INTEGER;
    v_shares INTEGER;
BEGIN
    SELECT total_points, total_shares INTO v_points, v_shares
    FROM user_points
    WHERE user_id = auth.uid();

    RETURN jsonb_build_object(
        'total_points', COALESCE(v_points, 0),
        'total_shares', COALESCE(v_shares, 0)
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP FUNCTION IF EXISTS record_share_and_award_points(TEXT);
CREATE OR REPLACE FUNCTION record_share_and_award_points(
    p_share_channel TEXT DEFAULT 'unknown'
)
RETURNS JSONB AS $$
DECLARE
    v_user_id UUID;
    v_last_share_at TIMESTAMP WITH TIME ZONE;
    v_total_points INTEGER;
    v_cooldown_minutes INTEGER := 5; 
BEGIN
    v_user_id := auth.uid();
    IF v_user_id IS NULL THEN
        RETURN jsonb_build_object('success', false, 'error', 'Unauthorized');
    END IF;

    SELECT last_share_at INTO v_last_share_at
    FROM user_points
    WHERE user_id = v_user_id;

    IF v_last_share_at IS NOT NULL AND (v_last_share_at + (v_cooldown_minutes || ' minutes')::interval) > NOW() THEN
        RETURN jsonb_build_object('success', false, 'error', 'Cooldown active');
    END IF;

    INSERT INTO share_history (user_id, share_channel, points_awarded)
    VALUES (v_user_id, p_share_channel, 5);

    INSERT INTO user_points (user_id, total_points, total_shares, last_share_at)
    VALUES (v_user_id, 5, 1, NOW())
    ON CONFLICT (user_id) DO UPDATE SET
        total_points = user_points.total_points + 5,
        total_shares = user_points.total_shares + 1,
        last_share_at = NOW()
    RETURNING total_points INTO v_total_points;

    RETURN jsonb_build_object('success', true, 'total_points', v_total_points);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 4. ADMIN RPC FOR BACKEND - DROP FIRST
DROP FUNCTION IF EXISTS record_share_and_award_points_admin(UUID, TEXT);
CREATE OR REPLACE FUNCTION record_share_and_award_points_admin(
    p_user_id UUID,
    p_share_channel TEXT DEFAULT 'unknown'
)
RETURNS JSONB AS $$
DECLARE
    v_last_share_at TIMESTAMP WITH TIME ZONE;
    v_total_points INTEGER;
    v_cooldown_minutes INTEGER := 5;
BEGIN
    SELECT last_share_at INTO v_last_share_at FROM user_points WHERE user_id = p_user_id;

    IF v_last_share_at IS NOT NULL AND (v_last_share_at + (v_cooldown_minutes || ' minutes')::interval) > NOW() THEN
        RETURN jsonb_build_object('success', false, 'error', 'Cooldown active');
    END IF;

    INSERT INTO share_history (user_id, share_channel, points_awarded, ip_hash)
    VALUES (p_user_id, p_share_channel, 5, 'admin_backend');

    INSERT INTO user_points (user_id, total_points, total_shares, last_share_at)
    VALUES (p_user_id, 5, 1, NOW())
    ON CONFLICT (user_id) DO UPDATE SET
        total_points = user_points.total_points + 5,
        total_shares = user_points.total_shares + 1,
        last_share_at = NOW()
    RETURNING total_points INTO v_total_points;

    RETURN jsonb_build_object('success', true, 'total_points', v_total_points);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 5. GRANTS
GRANT EXECUTE ON FUNCTION get_user_points() TO authenticated;
GRANT EXECUTE ON FUNCTION record_share_and_award_points(TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION record_share_and_award_points_admin(UUID, TEXT) TO authenticated, service_role;

NOTIFY pgrst, 'reload schema';
