-- ============================================
-- ADMIN AUDIT LOGS
-- ============================================

CREATE TABLE IF NOT EXISTS admin_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    admin_email TEXT,
    action TEXT NOT NULL,
    target_type TEXT,
    target_id TEXT,
    details JSONB,
    ip_address TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- RLS: Only admins can see logs
ALTER TABLE admin_audit_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admin: See all logs" 
ON admin_audit_logs 
FOR SELECT 
USING (auth.jwt() ->> 'email' = 'y220890@gmail.com');
