-- ============================================
-- QR NEXUS - ARCHITECTURE V5: FULL AUTH & AR/EN i18n
-- ============================================

-- 1. CLEANUP OLD SCHEMA
DROP TABLE IF EXISTS shops CASCADE;
DROP TABLE IF EXISTS nexus_identities CASCADE;
DROP TABLE IF EXISTS categories CASCADE;

-- 2. CORE CATEGORIES (Support for i18n names)
CREATE TABLE categories (
    id TEXT PRIMARY KEY,
    name_ar TEXT NOT NULL,
    name_en TEXT NOT NULL,
    icon TEXT,
    color TEXT,
    sort_order INTEGER DEFAULT 0
);

INSERT INTO categories (id, name_ar, name_en, icon, color, sort_order) VALUES
('restaurant', 'مطعم', 'Restaurant', '🍴', '#FF4D4D', 1),
('cafe', 'مقهى', 'Cafe', '☕', '#A67C52', 2),
('beauty', 'تجميل', 'Beauty', '💄', '#FF69B4', 3),
('fashion', 'أزياء', 'Fashion', '👗', '#9B59B6', 4),
('tech', 'تقنية', 'Tech', '💻', '#3498DB', 5),
('pharmacy', 'صيدلية', 'Pharmacy', '💊', '#2ECC71', 6),
('other', 'آخر', 'Other', '✨', '#F1C40F', 7);

-- 3. NID (NEXUS IDENTITIES) - Linked to Auth
CREATE TABLE nexus_identities (
    id TEXT PRIMARY KEY DEFAULT ('nx_' || substr(md5(random()::text), 1, 16)),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE, -- AUTH LINK
    full_name TEXT NOT NULL,
    bio TEXT,
    biometric_style TEXT DEFAULT 'neon-mesh',
    photo_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. CODES (The Vault Contents) - Strictly Linked
CREATE TABLE shops (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identity_id TEXT REFERENCES nexus_identities(id) ON DELETE CASCADE NOT NULL,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    name TEXT NOT NULL,
    url TEXT NOT NULL,
    category_id TEXT REFERENCES categories(id) DEFAULT 'other',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. ROW LEVEL SECURITY (RLS) - PUBLIC DISCOVERY
ALTER TABLE nexus_identities ENABLE ROW LEVEL SECURITY;
ALTER TABLE shops ENABLE ROW LEVEL SECURITY;

-- Policy: Everyone can READ identities
CREATE POLICY "Public: View Identities" ON nexus_identities FOR SELECT USING (true);
-- Policy: Only owners can manage identities
CREATE POLICY "Private: Manage My Identity" ON nexus_identities 
FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- Policy: Everyone can READ shops (visible via identities)
CREATE POLICY "Public: View Shops" ON shops FOR SELECT USING (true);
-- Policy: Only owners can manage shops
CREATE POLICY "Private: Manage My Shops" ON shops 
FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- 6. RPC: CREATE PROTECTED ENTITY
CREATE OR REPLACE FUNCTION create_user_identity(
    p_name TEXT,
    p_bio TEXT
)
RETURNS TEXT AS $$
DECLARE
    new_id TEXT;
BEGIN
    new_id := 'nx_' || substr(md5(random()::text), 1, 16);
    INSERT INTO nexus_identities (id, user_id, full_name, bio)
    VALUES (new_id, auth.uid(), p_name, p_bio);
    RETURN new_id;
END;
$$ LANGUAGE plpgsql;

-- 7. NOTIFY SCHEMA RELOAD
NOTIFY pgrst, 'reload schema';
